### ISSUE TITLE
Unable to locate weather file if downloaded to be used in benchmarking

### ISSUE THREAD

**Issue by abekhit** [LBNL-JCI-ICF/better#3]
In portfolio mode, if `use_default_benchmark_data=False` in run_single(...)[1], the benchmark fails to use weather files again. It looks in Data/Weather/year.

**Comment by tsbyq** [comment]
Issue fixed, please review.

**Comment by abekhit** [comment]
- [x] Benchmark creation is before building benhcmarking 
- [x] It still run benchmarking twice. Is it once for each energy source?
